package io.github.thanospapapetrou.funcky.prelude


import io.github.thanospapapetrou.funcky.BaseSpec
import io.github.thanospapapetrou.funcky.runtime.FunckyBoolean
import io.github.thanospapapetrou.funcky.runtime.FunckyCharacter
import io.github.thanospapapetrou.funcky.runtime.FunckyNumber
import io.github.thanospapapetrou.funcky.runtime.FunckyValue
import io.github.thanospapapetrou.funcky.runtime.prelude.Combinators
import io.github.thanospapapetrou.funcky.runtime.types.FunckyFunctionType
import io.github.thanospapapetrou.funcky.runtime.types.FunckySimpleType
import spock.lang.Unroll

class CombinatorsSpec extends BaseSpec {
    @Unroll('Test s (expression: #expression)')
    def 'Test s'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                                                                                                                      || result
        '"funcky:combinators".s'                                                                                                                                                                                                                                        || Combinators.S
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".s)))'                                                                                                                                      || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))))'                                                                                                               || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                                                                                                               || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                                                                                                                 || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))) ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                       || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))) ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'                        || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s)))) ("funcky:types".range ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))' || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s)))) ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".s))))'   || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))) ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))))'                       || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))) ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))))'                        || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s)))) ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".s))))' || FunckyBoolean.FALSE
        '"funcky:types".type ("funcky:combinators".s "funcky:numbers".add)'                                                                                                                                                                                             || new FunckyFunctionType(new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER), FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".s "funcky:booleans".and)'                                                                                                                                                                                            || new FunckyFunctionType(new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN), FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:commons".string ("funcky:combinators".s ("funcky:commons".error "foo"))'                                                                                                                                                                               || engine.converter.convert('"funcky:combinators".s ("funcky:commons".error "foo")')
        '"funcky:types".type ("funcky:combinators".s "funcky:numbers".add "funcky:numbers".plus)'                                                                                                                                                                       || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".s "funcky:booleans".and "funcky:booleans".not)'                                                                                                                                                                      || new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:commons".string ("funcky:combinators".s "funcky:numbers".add ("funcky:commons".error "foo"))'                                                                                                                                                          || engine.converter.convert('"funcky:combinators".s "funcky:numbers".add ("funcky:commons".error "foo")')
        '"funcky:combinators".s "funcky:numbers".add "funcky:numbers".plus 1'                                                                                                                                                                                           || new FunckyNumber(2.0G)
        '"funcky:combinators".s "funcky:numbers".add "funcky:numbers".plus 2'                                                                                                                                                                                           || new FunckyNumber(4.0G)
        '"funcky:combinators".s "funcky:numbers".add "funcky:numbers".minus 1'                                                                                                                                                                                          || new FunckyNumber(0.0G)
        '"funcky:combinators".s "funcky:numbers".add "funcky:numbers".minus 2'                                                                                                                                                                                          || new FunckyNumber(0.0G)
        '"funcky:combinators".s "funcky:numbers".subtract "funcky:numbers".plus 1'                                                                                                                                                                                      || new FunckyNumber(0.0G)
        '"funcky:combinators".s "funcky:numbers".subtract "funcky:numbers".plus 2'                                                                                                                                                                                      || new FunckyNumber(0.0G)
        '"funcky:combinators".s "funcky:numbers".subtract "funcky:numbers".minus 1'                                                                                                                                                                                     || new FunckyNumber(2.0G)
        '"funcky:combinators".s "funcky:numbers".subtract "funcky:numbers".minus 2'                                                                                                                                                                                     || new FunckyNumber(4.0G)
        '"funcky:combinators".s "funcky:booleans".and "funcky:booleans".not "funcky:booleans".false'                                                                                                                                                                    || FunckyBoolean.FALSE
        '"funcky:combinators".s "funcky:booleans".and "funcky:booleans".not "funcky:booleans".true'                                                                                                                                                                     || FunckyBoolean.FALSE
        '"funcky:combinators".s "funcky:booleans".or "funcky:booleans".not "funcky:booleans".false'                                                                                                                                                                     || FunckyBoolean.TRUE
        '"funcky:combinators".s "funcky:booleans".or "funcky:booleans".not "funcky:booleans".true'                                                                                                                                                                      || FunckyBoolean.TRUE
    }

    @Unroll('Test k (expression: #expression)')
    def 'Test k'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                                                || result
        '"funcky:combinators".k'                                                                                                                                                                  || Combinators.K
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".type "funcky:combinators".k))'                                                                                        || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".k)))'                                                                 || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".k)))'                                                                  || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".type "funcky:combinators".k)) ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".k)))'  || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".type "funcky:combinators".k)) ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".k)))' || FunckyBoolean.FALSE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".type ("funcky:combinators".k 0)))'                                                                                    || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".type ("funcky:combinators".k 0))'                                                                                                                   || FunckySimpleType.NUMBER
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".type ("funcky:combinators".k \'a\')))'                                                                                || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".type ("funcky:combinators".k \'a\'))'                                                                                                               || FunckySimpleType.CHARACTER
        '"funcky:commons".string ("funcky:combinators".k ("funcky:commons".error "foo"))'                                                                                                         || engine.converter.convert('"funcky:combinators".k ("funcky:commons".error "foo")')
        '"funcky:combinators".k 0 \'a\''                                                                                                                                                          || new FunckyNumber(0.0G)
        '"funcky:combinators".k \'a\' 0'                                                                                                                                                          || new FunckyCharacter('a' as char)
        '"funcky:combinators".k 0 ("funcky:commons".error "foo")'                                                                                                                                 || new FunckyNumber(0.0G)
        '"funcky:combinators".k \'a\' ("funcky:commons".error "foo")'                                                                                                                             || new FunckyCharacter('a' as char)
    }

    @Unroll('Test i (expression: #expression)')
    def 'Test i'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                        || result
        '"funcky:commons".string ("funcky:combinators".i)'                                                                                                                || engine.converter.convert('"funcky:combinators".s "funcky:combinators".k "funcky:combinators".k')
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".type "funcky:combinators".i))'                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".type "funcky:combinators".i))'                                                                 || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".type "funcky:combinators".i)) ("funcky:types".range ("funcky:types".type "funcky:combinators".i))' || FunckyBoolean.TRUE
        '"funcky:combinators".i 0'                                                                                                                                        || new FunckyNumber(0.0G)
        '"funcky:combinators".i 1'                                                                                                                                        || new FunckyNumber(1.0G)
        '"funcky:combinators".i \'a\''                                                                                                                                    || new FunckyCharacter('a' as char)
        '"funcky:combinators".i \'b\''                                                                                                                                    || new FunckyCharacter('b' as char)
    }

    @Unroll('Test b (expression: #expression)')
    def 'Test b'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                                                                                                                      || result
        '"funcky:commons".string "funcky:combinators".b'                                                                                                                                                                                                                || engine.converter.convert('"funcky:combinators".s ("funcky:combinators".k "funcky:combinators".s) "funcky:combinators".k')
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".b)))'                                                                                                                                      || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".b)))'                                                                                                                                       || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                                                                                                               || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                                                                                                                 || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".b))) ("funcky:types".range ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                        || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".b))) ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                          || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b)))) ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))' || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".b))) ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".b)))'                                               || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".b))) ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                       || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".b))) ("funcky:types".domain ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".b))))'                        || FunckyBoolean.FALSE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type ("funcky:combinators".b "funcky:numbers".minus))))'                                                                                                             || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".domain ("funcky:types".type ("funcky:combinators".b "funcky:numbers".minus)))'                                                                                                                                            || FunckySimpleType.NUMBER
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".type ("funcky:combinators".b "funcky:numbers".minus))))'                                                                                                              || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".range ("funcky:types".type ("funcky:combinators".b "funcky:numbers".minus)))'                                                                                                                                             || FunckySimpleType.NUMBER
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type ("funcky:combinators".b "funcky:booleans".not))))'                                                                                                              || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".domain ("funcky:types".type ("funcky:combinators".b "funcky:booleans".not)))'                                                                                                                                             || FunckySimpleType.BOOLEAN
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".type ("funcky:combinators".b "funcky:booleans".not))))'                                                                                                               || FunckyBoolean.TRUE
        '"funcky:types".range ("funcky:types".range ("funcky:types".type ("funcky:combinators".b "funcky:booleans".not)))'                                                                                                                                              || FunckySimpleType.BOOLEAN
        '"funcky:types".type ("funcky:combinators".b "funcky:numbers".minus "funcky:numbers".minus)'                                                                                                                                                                    || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".b "funcky:booleans".not "funcky:booleans".not)'                                                                                                                                                                      || new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:lists".empty ("funcky:commons".string ("funcky:combinators".b ("funcky:commons".error "foo")))'                                                                                                                                                        || FunckyBoolean.FALSE
        '"funcky:lists".empty ("funcky:commons".string ("funcky:combinators".b "funcky:numbers".minus ("funcky:commons".error "foo")))'                                                                                                                                 || FunckyBoolean.FALSE
        '"funcky:combinators".b ("funcky:numbers".add 1) "funcky:numbers".minus 2'                                                                                                                                                                                      || new FunckyNumber(-1.0G)
        '"funcky:combinators".b ("funcky:types".Function "funcky:types".Type) "funcky:types".type 1'                                                                                                                                                                    || new FunckyFunctionType(FunckySimpleType.TYPE, FunckySimpleType.NUMBER)
    }

    @Unroll('Test c (expression: #expression)')
    def 'Test c'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                                                                                                                      || result
        '"funcky:commons".string "funcky:combinators".c'                                                                                                                                                                                                                || engine.converter.convert('"funcky:combinators".s ("funcky:combinators".s ("funcky:combinators".k ("funcky:combinators".s ("funcky:combinators".k "funcky:combinators".s) "funcky:combinators".k)) "funcky:combinators".s) ("funcky:combinators".k "funcky:combinators".k)')
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".c)))'                                                                                                                                      || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))))'                                                                                                               || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".c)))'                                                                                                                                       || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".c))))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".c))))'                                                                                                                 || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))) ("funcky:types".domain ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".c))))'                        || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c)))) ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".c)))'                        || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c)))) ("funcky:types".range ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".c))))'   || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))) ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))))'                       || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))) ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))))'                        || FunckyBoolean.FALSE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c)))) ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".c))))' || FunckyBoolean.FALSE
        '"funcky:types".type ("funcky:combinators".c "funcky:numbers".add)'                                                                                                                                                                                             || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".c "funcky:booleans".and)'                                                                                                                                                                                            || new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:types".type ("funcky:combinators".c "funcky:numbers".add 0)'                                                                                                                                                                                           || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".c "funcky:booleans".and "funcky:booleans".false)'                                                                                                                                                                    || new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:lists".empty ("funcky:commons".string ("funcky:combinators".c ("funcky:commons".error "foo")))'                                                                                                                                                        || FunckyBoolean.FALSE
        '"funcky:lists".empty ("funcky:commons".string ("funcky:combinators".c "funcky:numbers".add ("funcky:commons".error "foo")))'                                                                                                                                   || FunckyBoolean.FALSE
        '"funcky:combinators".c "funcky:numbers".subtract 1 3'                                                                                                                                                                                                          || new FunckyNumber(2.0G)
        '"funcky:combinators".c "funcky:types".Function "funcky:types".Type "funcky:types".Number'                                                                                                                                                                      || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.TYPE)
    }

    @Unroll('Test w (expression: #expression)')
    def 'Test w'(final String expression, final FunckyValue result) {
        expect:
        engine.eval(expression) == result
        where:
        expression                                                                                                                                                                                                                                || result
        '"funcky:commons".string "funcky:combinators".w'                                                                                                                                                                                          || engine.converter.convert('"funcky:combinators".s "funcky:combinators".s ("funcky:combinators".s "funcky:combinators".k)')
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".w)))'                                                                                                                || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))))'                                                                                         || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))))'                                                                                          || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".w)))'                                                                                                                 || FunckyBoolean.TRUE
        '"funcky:types".typeVariable ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".w)))'                                                                                                                  || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))) ("funcky:types".domain ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))))' || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))) ("funcky:types".domain ("funcky:types".range ("funcky:types".type "funcky:combinators".w)))'                         || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".w)))) ("funcky:types".range ("funcky:types".range ("funcky:types".type "funcky:combinators".w)))'    || FunckyBoolean.TRUE
        '"funcky:commons".equal ("funcky:types".domain ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))) ("funcky:types".range ("funcky:types".range ("funcky:types".domain ("funcky:types".type "funcky:combinators".w))))'  || FunckyBoolean.FALSE
        '"funcky:types".type ("funcky:combinators".w "funcky:numbers".add)'                                                                                                                                                                       || new FunckyFunctionType(FunckySimpleType.NUMBER, FunckySimpleType.NUMBER)
        '"funcky:types".type ("funcky:combinators".w "funcky:booleans".and)'                                                                                                                                                                      || new FunckyFunctionType(FunckySimpleType.BOOLEAN, FunckySimpleType.BOOLEAN)
        '"funcky:lists".empty ("funcky:commons".string ("funcky:combinators".w ("funcky:commons".error "foo")))'                                                                                                                                  || FunckyBoolean.FALSE
        '"funcky:combinators".w "funcky:numbers".add 1'                                                                                                                                                                                           || new FunckyNumber(2.0G)
        '"funcky:combinators".w "funcky:numbers".multiply 2'                                                                                                                                                                                      || new FunckyNumber(4.0G)
        '"funcky:combinators".w "funcky:booleans".and "funcky:booleans".true'                                                                                                                                                                     || FunckyBoolean.TRUE
    }
}
